/*
 * This file is generated by jOOQ.
 */
package com.trip_jr.tripJr.jooq.tables


import com.trip_jr.tripJr.jooq.Public
import com.trip_jr.tripJr.jooq.keys.RATE_PKEY
import com.trip_jr.tripJr.jooq.keys.RATE__FK_HOTEL
import com.trip_jr.tripJr.jooq.keys.RATE__RATE_HOTEL_ID_FKEY
import com.trip_jr.tripJr.jooq.tables.Hotel.HotelPath
import com.trip_jr.tripJr.jooq.tables.records.RateRecord

import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Rate(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RateRecord>?,
    parentPath: InverseForeignKey<out Record, RateRecord>?,
    aliased: Table<RateRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RateRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.rate</code>
         */
        val RATE: Rate = Rate()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RateRecord> = RateRecord::class.java

    /**
     * The column <code>public.rate.rate_id</code>.
     */
    val RATE_ID: TableField<RateRecord, UUID?> = createField(DSL.name("rate_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.rate.hotel_id</code>.
     */
    val HOTEL_ID: TableField<RateRecord, UUID?> = createField(DSL.name("hotel_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.rate.rate</code>.
     */
    val RATE_: TableField<RateRecord, Double?> = createField(DSL.name("rate"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>public.rate.month</code>.
     */
    val MONTH: TableField<RateRecord, Int?> = createField(DSL.name("month"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.rate.default_rate</code>.
     */
    val DEFAULT_RATE: TableField<RateRecord, Double?> = createField(DSL.name("default_rate"), SQLDataType.DOUBLE, this, "")

    private constructor(alias: Name, aliased: Table<RateRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RateRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RateRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.rate</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.rate</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.rate</code> table reference
     */
    constructor(): this(DSL.name("rate"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RateRecord>?, parentPath: InverseForeignKey<out Record, RateRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, RATE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RatePath : Rate, Path<RateRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RateRecord>?, parentPath: InverseForeignKey<out Record, RateRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<RateRecord>): super(alias, aliased)
        override fun `as`(alias: String): RatePath = RatePath(DSL.name(alias), this)
        override fun `as`(alias: Name): RatePath = RatePath(alias, this)
        override fun `as`(alias: Table<*>): RatePath = RatePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<RateRecord> = RATE_PKEY
    override fun getReferences(): List<ForeignKey<RateRecord, *>> = listOf(RATE__FK_HOTEL, RATE__RATE_HOTEL_ID_FKEY)

    private lateinit var _fkHotel: HotelPath

    /**
     * Get the implicit join path to the <code>public.hotel</code> table, via
     * the <code>fk_hotel</code> key.
     */
    fun fkHotel(): HotelPath {
        if (!this::_fkHotel.isInitialized)
            _fkHotel = HotelPath(this, RATE__FK_HOTEL, null)

        return _fkHotel;
    }

    val fkHotel: HotelPath
        get(): HotelPath = fkHotel()

    private lateinit var _rateHotelIdFkey: HotelPath

    /**
     * Get the implicit join path to the <code>public.hotel</code> table, via
     * the <code>rate_hotel_id_fkey</code> key.
     */
    fun rateHotelIdFkey(): HotelPath {
        if (!this::_rateHotelIdFkey.isInitialized)
            _rateHotelIdFkey = HotelPath(this, RATE__RATE_HOTEL_ID_FKEY, null)

        return _rateHotelIdFkey;
    }

    val rateHotelIdFkey: HotelPath
        get(): HotelPath = rateHotelIdFkey()
    override fun `as`(alias: String): Rate = Rate(DSL.name(alias), this)
    override fun `as`(alias: Name): Rate = Rate(alias, this)
    override fun `as`(alias: Table<*>): Rate = Rate(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Rate = Rate(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Rate = Rate(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Rate = Rate(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Rate = Rate(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Rate = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Rate = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Rate = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Rate = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Rate = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Rate = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Rate = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Rate = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Rate = where(DSL.notExists(select))
}
