/*
 * This file is generated by jOOQ.
 */
package com.trip_jr.tripJr.jooq


import com.trip_jr.tripJr.jooq.tables.Amenity
import com.trip_jr.tripJr.jooq.tables.Booking
import com.trip_jr.tripJr.jooq.tables.Hotel
import com.trip_jr.tripJr.jooq.tables.HotelClaim
import com.trip_jr.tripJr.jooq.tables.Location
import com.trip_jr.tripJr.jooq.tables.Rate
import com.trip_jr.tripJr.jooq.tables.Review
import com.trip_jr.tripJr.jooq.tables.Room
import com.trip_jr.tripJr.jooq.tables.Users

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.amenity</code>.
     */
    val AMENITY: Amenity get() = Amenity.AMENITY

    /**
     * The table <code>public.booking</code>.
     */
    val BOOKING: Booking get() = Booking.BOOKING

    /**
     * The table <code>public.hotel</code>.
     */
    val HOTEL: Hotel get() = Hotel.HOTEL

    /**
     * The table <code>public.hotel_claim</code>.
     */
    val HOTEL_CLAIM: HotelClaim get() = HotelClaim.HOTEL_CLAIM

    /**
     * The table <code>public.location</code>.
     */
    val LOCATION: Location get() = Location.LOCATION

    /**
     * The table <code>public.rate</code>.
     */
    val RATE: Rate get() = Rate.RATE

    /**
     * The table <code>public.review</code>.
     */
    val REVIEW: Review get() = Review.REVIEW

    /**
     * The table <code>public.room</code>.
     */
    val ROOM: Room get() = Room.ROOM

    /**
     * The table <code>public.users</code>.
     */
    val USERS: Users get() = Users.USERS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Amenity.AMENITY,
        Booking.BOOKING,
        Hotel.HOTEL,
        HotelClaim.HOTEL_CLAIM,
        Location.LOCATION,
        Rate.RATE,
        Review.REVIEW,
        Room.ROOM,
        Users.USERS
    )
}
