/*
 * This file is generated by jOOQ.
 */
package com.trip_jr.tripJr.jooq.tables.references


import com.trip_jr.tripJr.jooq.tables.Hotel
import com.trip_jr.tripJr.jooq.tables.Location



/**
 * The table <code>public.hotel</code>.
 */
val HOTEL: Hotel = Hotel.HOTEL

/**
 * The table <code>public.location</code>.
 */
val LOCATION: Location = Location.LOCATION
